name: Deploy to shinyapps.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rsconnect-python

      - name: Deploy to shinyapps.io
        env:
          RSCONNECT_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          RSCONNECT_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          RSCONNECT_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          rsconnect add --account "$RSCONNECT_ACCOUNT" --name "$RSCONNECT_ACCOUNT" --token "$RSCONNECT_TOKEN" --secret "$RSCONNECT_SECRET"
          rsconnect deploy shiny . --name a11y-dashboard 